#!/bin/bash

help() {
echo "lab21 [OPTIONS] source_filename count start_char"
echo "Generation of a set number of copies of the specified file."
echo "Copy names are generated by adding the next letter or number to the name of"
echo "the source file, starting with the specified letter or number."
echo "Options:"
echo "  -h, --help	show this help message and exit"
}

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    help
    exit 0
fi
if [ "$#" -ne 3 ]; then
    help
    exit 1
fi

source_filename="$1"
count="$2"
start_char="$3"

if [[ ${#start_char} -ne 1 ]] && ! [[ $start_char =~ ^[0-9]+$ ]]; then
    echo "Error: Starting letter or digit for file names must be a single character or a digit."
    exit 2
fi
if [ ! -f "$source_filename" ]; then
    echo "Error: file '$source_filename' does not exist."
    exit 3
fi
if [[ $start_char =~ ^[0-9]+$ ]]; then
    while [ $count -gt 0 ]; do
        count=$(($count - 1))
        new_filename="${source_filename%.*}${start_char}${source_filename##*.}"
        cp "$source_filename" "$new_filename"
        start_char=$((start_char + 1))
    done
else
    plus=""
    ii=0
    for ((i=0; i<count; i++)); do
        current_char=$(echo -n "$start_char" | od -An -tuC)
        current_ascii=$((current_char + ii))
        z_ascii=$(echo -n "z" | od -An -tuC)
        Z_ascii=$(echo -n "Z" | od -An -tuC)
        if [[ $current_ascii -eq $((z_ascii + 1)) ]] || [[ $current_ascii -eq $((Z_ascii + 1)) ]]; then
            if [[ $current_ascii -eq $((z_ascii + 1)) ]]; then
                plus="${plus}z"
            else
                plus="${plus}Z"
            fi
            ii=$((ii - 26))
            current_ascii=$((current_ascii - 26))
        fi
        hex_code=$(printf "%x" $((current_ascii)))
        char=$(printf "\\x$hex_code")
        new_filename="${source_filename%.*}${plus}${char}.${source_filename##*.}"
        cp "$source_filename" "$new_filename"
        ii=$((ii + 1))
    done
fi
