import argparse

parser = argparse.ArgumentParser(usage='lab21 [OPTIONS] filename count start_char',
                                 description='''Generation of a set number of copies of the specified file.
                                 Copy names are generated by adding the next letter or number to the name of
                                 the source file, starting with the specified letter or number.''')
parser.add_argument('source_filename', help='The source file to copy.')
parser.add_argument('count', help='Number of files to create.')
parser.add_argument('start_char', help='Starting letter or digit for file names.')
args = parser.parse_args()
source_filename = str(args.source_filename)
count = int(args.count)
start_char = args.start_char
# проверяю корректность введённых данных
if len(start_char) != 1 and not start_char.isdigit():
    print("Error: Starting letter or digit for file names must be a single character or a digit.")
    exit(1)
# проверяю существование файла для копирования и в случае успеха копирую его содержимое
try:
    with open(source_filename, 'r', encoding='utf-8') as file:
        file_text = file.read()
except FileNotFoundError:
    print(f"Error: file '{source_filename}' not found.")
    exit(1)
# определяю, по какому правилу должно задаваться имя, и создаю файл
for i in range(count):
    if start_char.isalpha():
        new_filename = f"{source_filename[:source_filename.index('.')]}{chr(ord(start_char) + i)}{source_filename[source_filename.index('.'):]}"
    else:
        try:
            new_filename = f"{source_filename[:source_filename.index('.')]}{int(start_char) + i}{source_filename[source_filename.index('.'):]}"
        except ValueError:
            new_filename = f"{source_filename[:source_filename.index('.')]}{start_char}{i}{source_filename[source_filename.index('.'):]}"
    with open(new_filename, 'w', encoding='utf-8') as new_file:  # копирую содержимое файла
        new_file.write(file_text)
